name: Build S25 Ultra Kernel

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu bc flex bison
      - name: Configure
        run: |
          make CROSS_COMPILE=aarch64-linux-gnu- O=out s25ultra_defconfig
      - name: Build
        run: |
          make -j$(nproc) CROSS_COMPILE=aarch64-linux-gnu- O=out
      - name: Package
        run: |
          cp out/arch/arm64/boot/Image.gz-dtb kernel.img
          zip kernel-s25ultra-${{ github.sha }}.zip kernel.img
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kernel-build
          path: kernel-s25ultra-*.zip
